/**
 * Theme parity tests against upstream charmbracelet/huh v2.0.3 theme.go.
 *
 * fixtures/upstream-themes.json was generated by walking every lipgloss.Style
 * in each upstream theme (light and dark) with reflection and recording the
 * properties that differ from an empty style: fg, bg, left border colour,
 * border kind, bold, faint, SetString value, padding and margin.
 */
import { describe, test, expect } from "bun:test";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { stripAnsi, thickBorder, hiddenBorder, type Style } from "@oakoliver/lipgloss";
import {
  ThemeBase, ThemeCharm, ThemeDracula, ThemeBase16, ThemeCatppuccin, ThemeFunc,
  NewForm, NewGroup, NewInput, NewConfirm, type Styles,
} from "../src/index.js";
import { viewModel } from "./helpers.js";

type Info = Record<string, unknown>;

const upstream: Record<string, Record<string, Info>> = JSON.parse(
  readFileSync(join(import.meta.dir, "fixtures", "upstream-themes.json"), "utf8"),
);

const themes: Record<string, (isDark: boolean) => Styles> = {
  Base: ThemeBase,
  Charm: ThemeCharm,
  Dracula: ThemeDracula,
  Base16: ThemeBase16,
  Catppuccin: ThemeCatppuccin,
};

function col(c: unknown): string {
  if (c === null || c === undefined || c === "") return "";
  if (typeof c === "number") return String(c);
  if (typeof c === "string") {
    if (/^\d+$/.test(c)) return String(Number(c));
    return c.toLowerCase();
  }
  return String(c);
}

function borderName(s: Style): string {
  const b = s.getBorderStyle();
  if (b.left === thickBorder().left) return "thick";
  if (b.left === hiddenBorder().left) return "hidden";
  if (!b.left) return "";
  return "other";
}

// lipgloss < 1.1 lacks getBorderLeftForeground()/value(); fall back to the
// private fields so the test also runs against the older published build.
function borderLeftFg(s: Style): unknown {
  const a = s as any;
  return typeof a.getBorderLeftForeground === "function" ? a.getBorderLeftForeground() : a._borderLeftFg;
}
function styleValue(s: Style): string {
  const a = s as any;
  return typeof a.value === "function" ? a.value() : (a._value ?? "");
}

function info(s: Style): Info {
  const p = s.getPadding();
  const m = s.getMargin();
  const all: Info = {
    fg: col(s.getForeground()),
    bg: col(s.getBackground()),
    borderFg: col(borderLeftFg(s)),
    border: borderName(s),
    borderLeft: s.getBorderLeft(),
    bold: s.getBold(),
    faint: s.getFaint(),
    value: styleValue(s),
    padding: [p.top, p.right, p.bottom, p.left],
    margin: [m.top, m.right, m.bottom, m.left],
  };
  const defaults: Info = {
    fg: "", bg: "", borderFg: "", border: "", borderLeft: false, bold: false,
    faint: false, value: "", padding: [0, 0, 0, 0], margin: [0, 0, 0, 0],
  };
  const out: Info = {};
  for (const k of Object.keys(all)) {
    if (JSON.stringify(all[k]) !== JSON.stringify(defaults[k])) out[k] = all[k];
  }
  return out;
}

function isStyle(v: unknown): v is Style {
  return !!v && typeof (v as Style).render === "function" && typeof (v as Style).getForeground === "function";
}

function flatten(prefix: string, v: any, out: Record<string, Info>): void {
  if (isStyle(v)) {
    out[prefix] = info(v);
    return;
  }
  for (const k of Object.keys(v)) {
    if (k === "noneStyle") continue; // TS-only compatibility field
    flatten(prefix ? `${prefix}.${k}` : k, v[k], out);
  }
}

describe("themes match upstream theme.go", () => {
  for (const [name, fn] of Object.entries(themes)) {
    for (const mode of ["light", "dark"] as const) {
      const key = `${name}/${mode}`;
      test(key, () => {
        const ours: Record<string, Info> = {};
        flatten("", fn(mode === "dark"), ours);
        const want = upstream[key];
        expect(want).toBeDefined();
        // Same set of styles as the upstream Styles struct.
        expect(Object.keys(ours).sort()).toEqual(Object.keys(want).sort());
        for (const path of Object.keys(want)) {
          expect({ path, ...ours[path] }).toEqual({ path, ...want[path] });
        }
      });
    }
  }
});

// Readable spot-check table, transcribed by hand from theme.go.
// [theme, isDark, style path, fg, bg]
const table: Array<[string, boolean, string, string, string]> = [
  // ThemeCharm: indigo titles, green selections, cream-on-fuchsia buttons.
  ["Charm", true, "focused.title", "#7571f9", ""],
  ["Charm", false, "focused.title", "#5a56e0", ""],
  ["Charm", true, "focused.selectedOption", "#02bf87", ""],
  ["Charm", false, "focused.selectedOption", "#02ba84", ""],
  ["Charm", true, "focused.selectedPrefix", "#02a877", ""],
  ["Charm", false, "focused.selectedPrefix", "#02cf92", ""],
  ["Charm", true, "focused.focusedButton", "#fffdf5", "#f780e2"],
  ["Charm", false, "focused.focusedButton", "#fffdf5", "#f780e2"],
  ["Charm", true, "focused.blurredButton", "235", "252"],
  ["Charm", false, "focused.blurredButton", "252", "237"],
  ["Charm", true, "focused.errorMessage", "#ed567a", ""],
  ["Charm", false, "focused.errorMessage", "#ff4672", ""],
  ["Charm", true, "focused.selectSelector", "#f780e2", ""],
  ["Charm", true, "focused.description", "243", ""],
  ["Charm", false, "focused.description", "", ""],
  ["Charm", true, "focused.textInput.placeholder", "238", ""],
  ["Charm", false, "focused.textInput.placeholder", "248", ""],
  ["Charm", true, "focused.textInput.cursor", "#02bf87", ""],
  ["Charm", true, "group.title", "#7571f9", ""],
  // ThemeDracula
  ["Dracula", true, "focused.title", "#bd93f9", ""],
  ["Dracula", true, "focused.selectSelector", "#f1fa8c", ""],
  ["Dracula", true, "focused.focusedButton", "#f1fa8c", "#bd93f9"],
  ["Dracula", true, "focused.blurredButton", "#f8f8f2", "#282a36"],
  ["Dracula", true, "focused.description", "#6272a4", ""],
  // ThemeBase16
  ["Base16", true, "focused.title", "6", ""],
  ["Base16", true, "focused.focusedButton", "7", "5"],
  ["Base16", true, "blurred.title", "8", ""],
  ["Base16", true, "focused.textInput.placeholder", "8", ""], // upstream no-op assignments keep base
  ["Base16", true, "focused.textInput.prompt", "", ""],
  // ThemeCatppuccin (Mocha dark / Latte light)
  ["Catppuccin", true, "focused.title", "#cba6f7", ""],
  ["Catppuccin", false, "focused.title", "#8839ef", ""],
  ["Catppuccin", true, "focused.focusedButton", "#1e1e2e", "#f5c2e7"],
  ["Catppuccin", true, "focused.textInput.cursor", "#f5e0dc", ""],
  ["Catppuccin", true, "help.shortDesc", "#7f849c", ""],
  // ThemeBase
  ["Base", true, "focused.focusedButton", "0", "7"],
  ["Base", true, "focused.blurredButton", "7", "0"],
  ["Base", true, "focused.title", "", ""],
];

describe("theme colour table (from theme.go)", () => {
  for (const [name, dark, path, fg, bg] of table) {
    test(`${name}/${dark ? "dark" : "light"} ${path}`, () => {
      const flat: Record<string, Info> = {};
      flatten("", themes[name](dark), flat);
      expect(flat[path]?.fg ?? "").toBe(fg);
      expect(flat[path]?.bg ?? "").toBe(bg);
    });
  }
});

describe("field separator", () => {
  test("every built-in theme separates fields with a blank line", () => {
    for (const fn of Object.values(themes)) {
      expect(fn(true).fieldSeparator.render()).toBe("\n\n");
      expect(fn(false).fieldSeparator.render()).toBe("\n\n");
    }
  });

  test("rendered form has a blank line between fields", () => {
    let name = "";
    let ok = false;
    const f = NewForm(
      NewGroup(
        NewInput().title("Name").value(() => name, (v) => { name = v; }),
        NewConfirm().title("OK?").value(() => ok, (v) => { ok = v; }),
      ),
    ).withTheme(ThemeFunc(ThemeCharm));
    f.update(f.init());

    const lines = stripAnsi(viewModel(f)).split("\n").map((l) => l.trimEnd());
    const nameIdx = lines.findIndex((l) => l.includes("Name"));
    const okIdx = lines.findIndex((l) => l.includes("OK?"));
    expect(nameIdx).toBeGreaterThanOrEqual(0);
    expect(okIdx).toBeGreaterThan(nameIdx);
    // Input renders title + input line; then one blank separator line.
    expect(lines[nameIdx + 1]).toContain(">");
    expect(lines[nameIdx + 2]).toBe("");
    expect(okIdx).toBe(nameIdx + 3);
  });
});
